//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstanaCheTamBrat.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pages
    {
        public System.Guid page_id { get; set; }
        public string page_url { get; set; }
        public string page_title { get; set; }
        public string page_meta_description { get; set; }
        public string page_meta_keywords { get; set; }
        public string page_content { get; set; }
        public System.Guid provider_id { get; set; }
    
        public virtual providers providers { get; set; }
    }
}
