//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstanaCheTamBrat.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class providers_temp
    {
        public System.Guid provider_id { get; set; }
        public string provider_name { get; set; }
        public string provider_email { get; set; }
        public string provider_phone { get; set; }
        public string provider_short_description { get; set; }
        public Nullable<int> provider_rating_good { get; set; }
        public Nullable<int> provider_rating_bad { get; set; }
        public string provider_full_description { get; set; }
        public Nullable<int> provider_minimum_price { get; set; }
        public Nullable<int> provider_average_delivery_minutes { get; set; }
        public string provider_url { get; set; }
        public Nullable<bool> provider_approved { get; set; }
        public string provider_password { get; set; }
        public string provider_contact { get; set; }
        public string provider_address { get; set; }
    }
}
