//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstanaCheTamBrat.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.provider_requests = new HashSet<provider_requests>();
        }
    
        public System.Guid user_id { get; set; }
        public string user_phone { get; set; }
        public string user_name { get; set; }
        public string user_address { get; set; }
        public string user_comment { get; set; }
        public Nullable<System.Guid> user_parse_id { get; set; }
        public string user_platform { get; set; }
    
        public virtual ICollection<provider_requests> provider_requests { get; set; }
    }
}
